### ISSUE TITLE
Mailgun out of sandbox

### ISSUE THREAD

**Issue by lucymk** [Catapillr/loan-application-platform#65]
Once Phil adds his details to the MG account, we need to update it from the sandbox env

**Comment by maxgerber** [comment]
Hi @PHILCATAPILLR, 

I'm currently setting up the email API which will allow us to send messages from a `@catapillr.com` email address to users of the platform for verification, notifications, etc.

In order to get this to work, I'm going to need to add some details to your catapillr.com domain name account.

Would you be able to temporarily change the password for your domain name provider's account so that I can update these details? This is where you bought "catapillr.com" and is not necessarily where you host your current site, and might be something like [goDaddy](https://uk.godaddy.com/) or [namecheap](https://www.namecheap.com/). If you're not comfortable with this, I could try walking you through the steps required on a Google Hangouts or something.

All the best,
Max
